import type { MetadataRoute } from "next";

/**
 * PWA installability (2026-09-19) — "install AORMS Pulse on a phone's home
 * screen" request. This is a home-screen shortcut into the existing Next.js
 * app (Chrome's "Add to Home Screen"/install-banner flow), not a true
 * Android App Widget (a native glanceable/resizable home-screen tile) —
 * that would need a real Android/Kotlin project this repo doesn't have;
 * explicitly not what was built here, see this session's own discussion.
 *
 * `start_url: "/pulse"` — the installed icon opens straight to the Pulse
 * dashboard (roleHome() for every staff role already points there); an
 * unauthenticated tap redirects to /login exactly like visiting the URL
 * directly would, which is the expected/only sane behavior for an
 * installed shortcut into an authenticated app.
 *
 * Icons generated by scripts/generate-pwa-icons.mjs from the existing
 * AORMS mark (public/aorms-mark.png), composited onto Carbon Blue 60
 * (#0f62fe, this app's existing Carbon interactive/link color — no new
 * brand color introduced). "maskable" variants keep the mark inside the
 * ~80% safe zone Android's icon-masking can crop to; "any" variants are
 * used everywhere else (e.g. desktop install, iOS home screen).
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "AORMS Pulse",
    short_name: "Pulse",
    description: "Office KPIs, approvals, and ESTI's deterministic task-prediction scoring — your practice's daily brief.",
    start_url: "/pulse",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#ffffff",
    theme_color: "#0f62fe",
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/icon-maskable-192.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
      { src: "/icons/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
