/**
 * AORMS blog — post registry. Content is authored as structured blocks (same
 * pattern as the landing page's content arrays) rather than raw markdown, so
 * every post renders in pure Carbon typography with no extra rendering
 * dependency. Keep posts grounded in what the product actually does — see
 * docs/esti/NEXTJS-MIGRATION-PHASE*-AUDIT.md and CLAUDE.md for the source of
 * truth on every claim made here.
 */

export type BlogBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "list"; items: readonly string[] }
  | { type: "quote"; text: string; cite?: string };

export interface BlogPost {
  slug: string;
  title: string;
  /** One line for the list page and meta description. */
  dek: string;
  /** ISO date, also used for the JSON-LD datePublished. */
  date: string;
  /** Reading-time estimate, minutes. */
  readingMinutes: number;
  /** Sheet-index style tag, matching the landing page's drawing-set voice. */
  sheet: string;
  tags: readonly string[];
  body: readonly BlogBlock[];
}

export const BLOG_POSTS: readonly BlogPost[] = [
  {
    slug: "one-record-not-six-apps",
    title: "One record, not six apps: what fee recovery actually costs a practice",
    dek: "A fee proposal, a phase, and an invoice are one linked record in AORMS — not three documents in three tools that quietly drift apart.",
    date: "2026-08-20",
    readingMinutes: 6,
    sheet: "B-01",
    tags: ["Practice management", "Finance"],
    body: [
      {
        type: "p",
        text: "Most architecture practices don't lose fees to bad clients. They lose fees to their own paper trail: a fee proposal lives in a Word doc, the phase-wise schedule lives in a spreadsheet someone updates by hand, and the invoice gets typed into accounting software as a fresh line item with no link back to either. Three documents, three tools, and nothing enforcing that they agree with each other.",
      },
      {
        type: "p",
        text: "The failure mode is boring and specific: a phase is invoiced at the wrong percentage because the spreadsheet wasn't updated after a scope revision, or a client disputes an invoice and nobody can produce the proposal clause it was billed against without searching an inbox.",
      },
      { type: "h2", text: "What \"one record\" means in AORMS" },
      {
        type: "p",
        text: "AORMS's proposals namespace unifies what used to be two separate ideas — a COA fee proposal and a scope agreement — into a single esti_proposal model. A project's invoices reference that proposal and a specific phase directly, by ID, not by re-typing a number. When a proposal changes, the phases it defines change with it; when an invoice is raised, it draws its phase percentage and fee basis straight from the proposal record, not from someone's memory of the last revision.",
      },
      {
        type: "list",
        items: [
          "A fee proposal references its project.",
          "A phase is defined once, on the proposal, and reused everywhere it's billed against.",
          "An invoice references its proposal and phase — the amount traces back to the clause that earned it.",
        ],
      },
      { type: "h2", text: "The client-approval gate" },
      {
        type: "p",
        text: "Proposals in AORMS carry a client-approval gate (setClientApproval) as part of the Project OS flow — a project doesn't move from proposal to active delivery on a verbal \"sounds good,\" it moves on a recorded approval tied to the actual proposal document the client saw. That approval, and the proposal it approves, stay attached to the project permanently — not filed away in an email thread that gets harder to search every month.",
      },
      {
        type: "quote",
        text: "Nothing re-typed, nothing drifts out of sync, and every rupee owed traces back to the drawing that earned it.",
      },
      {
        type: "p",
        text: "None of this is a workflow bolted onto generic project-management software. It's the actual shape of how an Indian architecture practice bills a project — proposal, phase, invoice, linked — modeled directly, so the software enforces the discipline a spreadsheet only hopes for.",
      },
    ],
  },
  {
    slug: "frozen-invoice-gst-tds",
    title: "Why an AORMS invoice never quietly changes after you send it",
    dek: "GST and TDS figures are frozen onto the invoice at the moment it's raised — editing your firm or client record later can't rewrite a document a client already has.",
    date: "2026-08-27",
    readingMinutes: 5,
    sheet: "B-02",
    tags: ["GST/TDS", "Compliance"],
    body: [
      {
        type: "p",
        text: "A quiet bug pattern in a lot of billing software: the invoice PDF is generated by joining live firm and client records at render time. Fix a typo in your GSTIN six months later, and every historical invoice PDF silently re-renders with the corrected number — including invoices a client already filed with their accountant showing the old one. The document you can produce today no longer matches the document you actually sent.",
      },
      {
        type: "p",
        text: "AORMS invoices don't work that way. GST is not one number — it's a CGST/SGST split for an intra-state supply, or IGST for an inter-state one, decided by the place of supply under Rule 46(n) of the CGST Rules. TDS under Section 194J applies separately, on professional fees, deducted by the client rather than collected by the firm. Every one of those figures is computed once, at the moment the invoice is raised, and written onto the invoice record itself.",
      },
      { type: "h2", text: "What \"frozen\" means in practice" },
      {
        type: "list",
        items: [
          "CGST/SGST/IGST split — computed from the place of supply at issue time, stored on the invoice.",
          "Section 194J TDS — the deduction the client will make, recorded alongside the fee, not recalculated later.",
          "Firm and client details — snapshotted onto the invoice, not joined live from the current firm/client record.",
        ],
      },
      {
        type: "p",
        text: "Edit your firm's registered address, or a client's GSTIN, next month, and every invoice already issued keeps showing exactly what it showed the day it went out. Only new invoices pick up the correction. That's not a limitation — it's the compliance requirement. A tax document has to be reproducible exactly as issued, for GST returns, for the client's input tax credit claim, for an audit trail. A live join can't give you that; a frozen snapshot can.",
      },
      {
        type: "p",
        text: "It's a small mechanical detail, but it's the kind of detail that only gets built correctly when the person specifying the software has actually filed a GSTR return, not when \"add GST\" is a checkbox feature request.",
      },
    ],
  },
  {
    slug: "coa-fee-scale-enforcement",
    title: "The COA scale of charges isn't a PDF you have to remember — it's a gate",
    dek: "AORMS benchmarks every fee proposal against the Council of Architecture's minimum scale, and flags anything below it before it goes out, not after.",
    date: "2026-09-01",
    readingMinutes: 4,
    sheet: "B-03",
    tags: ["COA", "Fee proposals"],
    body: [
      {
        type: "p",
        text: "The Council of Architecture publishes a scale of charges — a minimum professional fee benchmark practices are expected to hold to. In most offices that scale lives as a PDF someone downloaded once, referenced from memory during a fee negotiation, and quietly forgotten under client pressure to \"just match what the other firm quoted.\"",
      },
      {
        type: "p",
        text: "AORMS encodes it as a function, not a memory: coaMinimumFee() computes the benchmark for a proposal, and isBelowCoaMinimum() checks a quoted fee against it. When a proposal is priced below that minimum, the system doesn't silently allow it and doesn't silently block it either — it requires an explicit, audited override. Someone in the practice has to actively record that they're quoting below scale, and why, rather than the discount happening by omission in a negotiation email nobody reads again.",
      },
      { type: "h2", text: "The same discipline at the lead stage" },
      {
        type: "p",
        text: "The same conflict-awareness runs earlier than the fee proposal itself — the leads.convert step that turns an inbound enquiry into a client and project carries a conflict-of-interest gate, so a practice doesn't discover a competing-client conflict after the engagement letter is already signed.",
      },
      {
        type: "list",
        items: [
          "coaMinimumFee() — computes the COA scale of charges benchmark for a proposal.",
          "isBelowCoaMinimum() — flags a quoted fee against that benchmark.",
          "Below-minimum quotes require an audited override, not a silent discount.",
        ],
      },
      {
        type: "p",
        text: "It's a small piece of the proposals namespace, but it's the difference between a compliance rule the practice is supposed to remember and a compliance rule the software actually enforces at the point a number gets typed in.",
      },
    ],
  },
  {
    slug: "esti-answers-from-your-own-records",
    title: "ESTI doesn't guess — it answers from your firm's own records, or it says nothing",
    dek: "The built-in AI agent is scoped to validated firm repositories. It isn't a public model with your practice's data quietly feeding it.",
    date: "2026-09-03",
    readingMinutes: 4,
    sheet: "B-04",
    tags: ["ESTI", "AI"],
    body: [
      {
        type: "p",
        text: "Every architecture practice now gets asked, at some point, whether its \"AI features\" are actually safe to use on client-confidential drawings, fee structures, and site data. It's a fair question, and most SaaS answers to it are vague on purpose.",
      },
      {
        type: "p",
        text: "ESTI — Embedded Studio Intelligence — is AORMS's built-in agent, and its scoping rule is specific: it answers only from validated firm repositories. Practically, that means the Knowledge Bank portal (PDF intake converted to markdown, then published) and a firm's own structured records are what ESTI can draw on — not the open internet, and not a shared training corpus across other firms' data.",
      },
      { type: "h2", text: "Where it actually runs" },
      {
        type: "p",
        text: "ESTI calls a self-hosted Ollama container that sits alongside the AORMS backend — not a third-party API, and not a model running on a user's own laptop. That matters for two reasons: firm data doesn't leave the deployment to reach the model, and the AI stays available and consistent regardless of which device someone signs in from, since it's cloud infrastructure rather than a local install.",
      },
      {
        type: "quote",
        text: "It never trains a third-party model on your data.",
      },
      {
        type: "p",
        text: "The product decision underneath this is simple: an AI feature in office software should be a extension of the firm's own knowledge, not a new place the firm's confidential information quietly ends up. ESTI is scoped, deliberately, to stay on the smaller side of that line.",
      },
    ],
  },
  {
    slug: "project-os-activation-gate",
    title: "A project doesn't go live on a handshake — the six checks behind Project OS",
    dek: "Before a lead becomes an active, billable project in AORMS, six specific conditions have to be true. None of them are optional, and none of them are manual memory.",
    date: "2026-09-04",
    readingMinutes: 5,
    sheet: "B-05",
    tags: ["Project OS", "Practice management"],
    body: [
      {
        type: "p",
        text: "\"We're basically starting the project\" is a phrase that causes more disputes in architecture practice than almost any other. Work begins informally — a site visit, a first concept sketch — before the paperwork that should have preceded it (a signed fee proposal, an approved DNA/brief, an advance payment) actually exists. Everyone remembers a different moment as \"the start.\"",
      },
      {
        type: "p",
        text: "AORMS models this transition explicitly, through what functions as the office hub's lead-to-activation pipeline. A project only crosses from proposal into active delivery once evaluateActivationGate() confirms all of the following are true:",
      },
      {
        type: "list",
        items: [
          "Status is PROPOSAL — the project hasn't already been activated.",
          "hasDna — the project's design brief/DNA record exists.",
          "hasAssessment — the relevant site or project assessment is on file.",
          "feeApproved — the fee proposal has been through the client-approval gate.",
          "onboardingComplete — client onboarding steps are actually finished, not just started.",
          "advancePaid — the advance payment has been recorded, not assumed.",
        ],
      },
      { type: "h2", text: "Why a gate, not a status dropdown" },
      {
        type: "p",
        text: "A status field a team member can set to \"Active\" by hand is exactly the mechanism that lets informal starts happen — someone flips the status because the client is pushing, and the missing brief or unpaid advance becomes everyone else's problem three months later. A gate that actually checks six underlying facts can't be talked past the same way. If advancePaid is false, the project isn't active, no matter how urgent the client sounds on the phone.",
      },
      {
        type: "p",
        text: "It's a small piece of plumbing most practices never see named, because most software doesn't bother modeling the moment at all — a lead either exists or it's a project, with nothing in between. AORMS treats that in-between state as the place most fee and scope disputes are actually born, and builds the gate accordingly.",
      },
    ],
  },
] as const;

export function getBlogPost(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug);
}

/** Posts sorted newest first — the list page's canonical order. */
export function blogPostsByDate(): readonly BlogPost[] {
  return [...BLOG_POSTS].sort((a, b) => (a.date < b.date ? 1 : -1));
}
